config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lmizrahi/etas:
      branch: main
      repo: https://github.com/lmizrahi/etas.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lmizrahi/etas git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-lilac-ant.sh
        container: qc.acc_sloppy-cinnamon-lynx
  QC.Doc:
    repos:
      github.com/lmizrahi/etas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-fuchsia-toucan.sh
        container: qc.doc_stuffy-crimson-mandrill
      github.com/lmizrahi/etas git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-buff-tarantula.sh
        container: qc.doc_flaky-sapphire-hound
      github.com/lmizrahi/etas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-ecru-moth.sh
        container: qc.doc_shaky-amethyst-gecko
  QC.Lic:
    repos:
      github.com/lmizrahi/etas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-malachite-devil.sh
        container: qc.lic_lousy-lilac-duck
  QC.Sec:
    repos:
      github.com/lmizrahi/etas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-beige-javanese.sh
        container: qc.sec_baggy-peach-chameleon
  QC.Sty:
    repos:
      github.com/lmizrahi/etas flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-pumpkin-starfish.sh
        container: qc.sty_wiggy-azure-buzzard
      github.com/lmizrahi/etas jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-thistle-havanese.sh
        container: qc.sty_cranky-gamboge-affenpinscher
  QC.Uni:
    repos:
      github.com/lmizrahi/etas pytest:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-gold-caracal.sh
        container: qc.uni_scaly-plum-boar
  QC.Ver:
    repos:
      github.com/lmizrahi/etas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-auburn-cat.sh
        container: qc.ver_thirsty-bistre-wasp
timeout: 5400
